---
sudo: required
language: python
python:
  - "2.7"
env:
  global:
    - ROLE_NAME: githubfoam.onos
  matrix:
    # - MOLECULE_DISTRO: centos74
    - MOLECULE_DISTRO: ubuntu1804
services:
  - docker
jobs:
  include:
    - stage: molecule test
      install:
        - sudo apt-get -qq update
      before_script:
        - sudo apt-get install python-virtualenv
      script:
        - virtualenv --no-site-packages myenv3
        - source myenv3/bin/activate
        - pip install -r requirements.txt
        - sudo molecule test
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
