---
sudo: required
language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
env:
  # - MOLECULE_SCENARIO=centos MOLECULE_USER=vagrant
  # - MOLECULE_SCENARIO=debian MOLECULE_USER=vagrant
  # - MOLECULE_SCENARIO=fedora MOLECULE_USER=vagrant
  # - MOLECULE_SCENARIO=ubuntu1804 MOLECULE_USER=vagrant
  - MOLECULE_SCENARIO=ubuntu1604
services:
  - docker
jobs:
  include:
    - stage: molecule lint
      install:
        - sudo apt-get -qq update
      before_script:
        - pip install -r requirements.txt
      script:
        - molecule lint --scenario-name ${MOLECULE_SCENARIO}
    - stage: molecule destroy
      script:
        - molecule destroy --scenario-name ${MOLECULE_SCENARIO}
    - stage: molecule create
      script:
        - molecule create --scenario-name ${MOLECULE_SCENARIO}
    - stage: molecule converge & verify
      script:
        - molecule converge --scenario-name ${MOLECULE_SCENARIO}
        # - molecule idempotence
        - molecule verify --scenario-name ${MOLECULE_SCENARIO}
    - stage: molecule syntax
      script:
        - molecule syntax --scenario-name ${MOLECULE_SCENARIO}
    - stage: molecule destroy
      script:
        - molecule destroy --scenario-name ${MOLECULE_SCENARIO}
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
