---
sudo: required
language: python
python:
  - "3.6"
  # PyPy versions
  # - "pypy3.5"
# matrix:
#     include:
#     - language: python
#       env: ISOLATED=true
    # - rvm: 2.0.0
    #   env: ISOLATED=true
env:
  global:
   - distribution=ubuntu
     version=18.04
   - COMMIT=${TRAVIS_COMMIT::8}
services:
  - docker
jobs:
  include:
    - stage:  molecule lint
      install:
        - galaxy_role_name="githubfoam.onos"
        - sudo pip install -r requirements.txt
        - sudo apt-add-repository ppa:ansible/ansible --yes
        - sudo apt-get -qq update
        - sudo apt-get install -y python-pip libssl-dev
        # - sudo pip install molecule docker-py
        - sudo ansible-galaxy install -p  /home/travis/build/githubfoam/ansible-role-onos githubfoam.onos
        - cd  /home/travis/build/githubfoam/ansible-role-onos/githubfoam.onos
        - sudo molecule init scenario --role-name githubfoam.onos
        - sudo molecule lint
        - sudo molecule destroy
    # - stage: molecule init
    #   script:
    #     - molecule init scenario --role-name githubfoam.onos
    # - stage: molecule destroy
    #   script:
    #     - molecule destroy
    # - stage: molecule destroy
    #   script:
    #     - sudo molecule destroy
after_success:
    - stage: Workflow ends
      script:
        - echo "success"
# Notify Ansible Galaxy when an ansible role builds successfully.
notifications:
  #email: false
   email:
     on_success: never # default: change
     on_failure: always # default: always
   webhooks: https://galaxy.ansible.com/api/v1/notifications/
