---
sudo: required
language: python
python:
  - "3.6"
env:
  global:
    - ROLE_NAME: githubfoam.onos
  matrix:
    # - MOLECULE_DISTRO: centos74
    - MOLECULE_DISTRO: ubuntu1804
services:
  - docker
jobs:
  include:
    - stage: molecule test
      install:
        - sudo apt-add-repository ppa:ansible/ansible --yes
        - sudo apt-get -qq update
        - sudo apt-get install -y python-pip libssl-dev
        - sudo pip install molecule docker-py
      before_script:
        - ls -la
      script:
        - sudo molecule test
after_success:
  - stage: Workflow ends
    script:
      - echo "success"

notifications:
  email:
    on_success: never
    on_failure: always
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
