---
sudo: required
language: python
python:
  - "2.7"
# virtualenv:
#   system_site_packages: true
env:
  - MOLECULE_SCENARIO=ubuntu1804
  - MOLECULE_SCENARIO=ubuntu1604
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - virtualenv --python=$(which python2.7) envmolecule
  - source envmolecule/bin/activate
  - pip install -r requirements.txt
script:
  - molecule test --scenario-name ${MOLECULE_SCENARIO}
# jobs:
#   include:
#     - stage: molecule test
#       # install:
#       #   - sudo apt-get -qq update
#       before_script:
#         # - virtualenv --no-site-packages --python=$(which python2.7) envmolecule-${MOLECULE_SCENARIO}
#         - virtualenv --python=$(which python2.7) envmolecule-${MOLECULE_SCENARIO}
#         - source envmolecule-${MOLECULE_SCENARIO}/bin/activate
#         - pip install -r requirements.txt
#         - sudo apt-get -qq update
#       script:
#         - molecule test --scenario-name ${MOLECULE_SCENARIO}
    # - stage: molecule destroy
    #   script:
    #     - molecule destroy --scenario-name ${MOLECULE_SCENARIO}
    # - stage: molecule create
    #   script:
    #     - source envmolecule-${MOLECULE_SCENARIO}/bin/activate
    #     - molecule create --scenario-name ${MOLECULE_SCENARIO}
    # - stage: molecule create & converge & verify
    #   before_script:
    #     - virtualenv --no-site-packages --python=$(which python2.7) envmolecule-${MOLECULE_SCENARIO}
    #     - source envmolecule-${MOLECULE_SCENARIO}/bin/activate
    #     - pip install -r requirements.txt
    #     - sudo apt-get -qq update
    #   script:
    #     - molecule create --scenario-name ${MOLECULE_SCENARIO}
    #     - molecule converge --scenario-name ${MOLECULE_SCENARIO}
    #     # - molecule idempotence
    #     - molecule verify --scenario-name ${MOLECULE_SCENARIO}
    # - stage: molecule syntax
    #   script:
    #     - molecule syntax --scenario-name ${MOLECULE_SCENARIO}
    # - stage: molecule destroy
      # script:
      #   - molecule destroy --scenario-name ${MOLECULE_SCENARIO}
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
