---
sudo: required
language: python
python:
  - "2.7"
  # - "3.6"
virtualenv:
  system_site_packages: true
env:
  global:
    - ROLE_NAME: githubfoam.onos
  matrix:
    # - MOLECULE_DISTRO: centos74
    # - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1804
services:
  - docker
jobs:
  include:
    - stage: molecule lint
      install:
        - sudo apt-get -qq update
      before_script:
        - pip install -r requirements.txt
      script:
        - molecule lint
    - stage: molecule destroy
      script:
        - molecule destroy
    - stage: molecule create
      script:
        - molecule create
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
