---
sudo: required
language: python
python:
  - "2.7"
env:
  - MOLECULE_SCENARIO=ubuntu
  # - MOLECULE_SCENARIO=ubuntu1604
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - virtualenv --python=$(which python2.7) envmolecule
  - source envmolecule/bin/activate
  - pip install -r requirements.txt
script:
  - molecule test --scenario-name ${MOLECULE_SCENARIO}
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
