---
sudo: required
language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
env:
  global:
    - ROLE_NAME: githubfoam.onos
  matrix:
    # - MOLECULE_DISTRO: centos74
    - MOLECULE_DISTRO: ubuntu1604
services:
  - docker
jobs:
  include:
    - stage: molecule test
      install:
        - sudo apt-get -qq update
      before_script:
        - pip install -r requirements.txt
        # - molecule test
      script:
        - molecule test
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
