FROM ubuntu:18.04
RUN sudo apt-get update && \
    sudo apt-get install -y software-properties-common && \
    sudo apt-add-repository ppa:ansible/ansible -y && \
    sudo apt-get update && \
    sudo apt-get install ansible -y
RUN ansible-galaxy install githubfoam.onos
