FROM ubuntu:18.04
RUN apt-get update && \
    apt-get install -y software-properties-common  \
    apt-add-repository --yes  ppa:ansible/ansible 
    #apt-get install ansible -y
#RUN ansible-galaxy install githubfoam.onos
