---
- name: tasks file for ansible-role-onos
  include_tasks: "{{ ansible_os_family }}-install.yml"
  when: ansible_os_family == 'Debian'
- name: configure onos.
  include_tasks: "configure-{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'Debian'
