---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu1604
    image: ubuntu:16.04
    # command: /sbin/init
    # capabilities:
    #   - SYS_ADMIN
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    groups:
      - DebianGrp
  - name: ubuntu1804
    image: ubuntu:18.04
    # command: /sbin/init
    # capabilities:
    #   - SYS_ADMIN
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    groups:
      - DebianGrp
provisioner:
  name: ansible
  group_vars:
    DebianGrp:
    ansible_become: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
